import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import "./globals.css";
import { Analytics } from "@vercel/analytics/next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  authors: [{ name: "Admin", email: "nathaniel.g.cowan@gmail.com" }],
};

export const admin = {
  name: "Nathaniel Cowan",
  email: "nathaniel.g.cowan@gmail.com",
};

import dynamic from "next/dynamic";
const BibleTranslations = dynamic(
  () => import("../components/BibleTranslations"),
  { ssr: false },
);
const BibleSearch = dynamic(() => import("../components/BibleSearch"), {
  ssr: false,
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <BibleSearch />
          <BibleTranslations />
          {children}
        </Providers>
      </body>
    </html>
  );
}
